# Build icon library, create zip file for release and create PR
name: icon library

on: workflow_dispatch

jobs:
  build-icon-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        - name: Setup Node.js environment
            uses: actions/setup-node@v3.6.0
            with:
              node-version: '20.3.1'
              registry-url: 'https://registry.npmjs.org'
      - name: Run Glypfig
        run: |
          npx glypfig \
            -a $API_KEY \
            -k $FILE_KEY \
            -n $NODE_ID \
            -f png,svg,react \
            -p \
            -t tsx \
            -h './release/icon-kit-template-react-tsx.eta' \
            -c 2.66 \
            -i 'Size=S'
        env:
          API_KEY: ${{ secrets.HDS_ICON_KIT }}
          FILE_KEY: 'Kxwg3R0zNRHj55nQqFu6VS'
          NODE_ID: '172:2478'
      - name: Bump version in Changelog
        run: |
          PKG_VER=`node -pe "require('./packages/react/package.json').version"`
          sed -i.bak -E "s/version [0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}/version ${PKG_VER}/" ./release/icon-kit-template-CHANGELOG.txt
      - name: Copy Changelog file
        run: cp ./release/icon-kit-template-CHANGELOG.txt ./icon-library/CHANGELOG.txt
      - name: Copy license file
        run: cp ./release/icon-kit-template-LICENSE.txt ./icon-library/LICENSE.txt
      - name: Create release zip file
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: 'release/hds-icon-kit.zip'
          path: './icon-library'
      - name: Copy svg files to repo folders
        run: cp ./icon-library/svg/* ./packages/core/src/svg
      - name: Copy react files to repo folders
        run: cp ./icon-library/react/* ./packages/react/src/icons
      - name: Install React package NPM dependencies
        run: npm install ./packages/react
      - name: Lint React files
        run: npx prettier --write './packages/react/src/icons/*.{ts,tsx}'
      - name: Code analysis for React files
        run: npx eslint -c './packages/react/.eslintrc.json' --ignore-path './packages/react/.eslintignore' --fix  './packages/react/src/icons/*.{ts,tsx}'
      - name: Remove icon library build directory
        run: rm -rf ./icon-library
      - name: Commit changed files
        run: |
          git config --global user.email "hds@hel.fi"
          git config --global user.name "Github Actions"
          git add .
          git commit -m 'Updated icon library'
          git push
      - name: create pull request
        run: gh pr create -B master --title 'Icon library build' --body 'Created by Github action icon library'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
