# Build icon library, zip file for release and create PR
name: Icon library build

on: workflow_dispatch

jobs:
  build-icon-library:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '19.6.0'
        registry-url: 'https://registry.npmjs.org'
        cache: yarn
    - name: Run Glypfig
      run: npx glypfig -a $API_KEY -k $FILE_KEY -n $NODE_ID -f png,svg,react -p -t tsx
      env:
        API_KEY: ${{ secrets.HDS_ICON_KIT }}
        FILE_KEY: 'Kxwg3R0zNRHj55nQqFu6VS'
        NODE_ID: '172:2478'
    - name: Create zip file
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: 'hds-icon-kit.zip'
        directory: './icon-library'
        path: './files'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Copy icon files to repo folders
      run: cp ./icon-library/svg/* ./packages/core/src/svg
      run: cp ./icon-library/react/* ./packages/react/src/icons
    - name: create pull request
      run: gh pr create -B master --title 'Icon library build' --body 'Created by Github action Icon library build'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
