name: Icon library build

on:
  workflow_dispatch:

jobs:
  build-icon-library:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        registry-url: "https://registry.npmjs.org"
    - name: Get icons
      run: node scripts/fetch-icon-library.js
    - name: Create PR
      run: echo 'done.'
