name: Icon library build

on: workflow_dispatch

jobs:
  build-icon-library:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        registry-url: "https://registry.npmjs.org"
    - uses: actions/checkout@v3
    - name: Get icons
      env:
          FIGMA_API_KEY: ${{ secrets.HDS_UI_KIT }}
      run: node scripts/fetch-icon-library.js
    - name: Create PR
      run: echo 'done.'
